### first test of the initialization of backend
POST http://localhost:3000/api/auth/login

### REgister 
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "first@mizuka.edu",
  "username":"First Teacher",
  "password": "password123",
  "role":"teacher",
  "institute_id":"1c8fb7e7-5e07-409d-8245-19b4b834028c"
}