const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
const PORT = process.env.PORT || 3000;
const authRoutes = require('./Routes/authRoutes');
app.use(cors());
app.use(express.json());
app.use('/api/auth/', authRoutes);
app.listen(PORT, '0.0.0.0', () => [console.log('Server listening at 3000')]);
