### Get chat history
GET http://localhost:3000/api/messages/1c8fb7e7-5e07-409d-8245-19b4b834028c
###
POST http://localhost:3000/api/institute/create
Content-Type: application/json

{
  "name": "Bonaventure High School",
  "adminId": "c7efe75a-8306-4b9b-8550-20f90ec8e62c"
}
### Create a New Private Channel (Admin Only)
POST http://localhost:3000/api/channel/create
Content-Type: application/json

{
  "name": "Damily Secret Lounge",
  "institute_id": "e158fe90-00ad-4b99-9416-9fa64e2fd967",
  "adminId": "c7efe75a-8306-4b9b-8550-20f90ec8e62c",
  "is_private": true
}

### Get the Global Invite Key
GET http://localhost:3000/api/institute/key/8ef44a8b-c24e-4730-8a6f-e042cba65e56

### Get the user info


GET http://localhost:3000/api/auth/user-info/c7efe75a-8306-4b9b-8550-20f90ec8e62c

### Search for members in an Institute
GET http://localhost:3000/api/institute/8ef44a8b-c24e-4730-8a6f-e042cba65e56/search-members?query=m&userId=c7efe75a-8306-4b9b-8550-20f90ec8e62c
Content-Type: application/json

###

### Get or Create P2P Room
POST http://localhost:3000/api/p2p/room
Content-Type: application/json

{
    "user1": "YOUR_USER_UUID",
    "user2": "TARGET_USER_UUID"
}