### first test of the initialization of backend
POST http://localhost:3000/api/auth/login

### REgister 
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "mzkhan886@gmail.com",
  "username":"Muhammad Zahooruddin Nizamani",
  "password": "boombech",
  "role":"teacher",
  "institute_id":"1c8fb7e7-5e07-409d-8245-19b4b834028c"
}
### LOGIN 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "mzkhan886@gmail.com",
  "password": "boombech"
}

### RESET PASSWORD

POST http://localhost:3000/api/auth/request-reset
Content-Type: application/json

{
  "email":"mzkhan886@gmail.com"
}
### TEST THE RESET PASSWORD
POST http://localhost:3000/api/auth/reset-password
Content-Type: application/json

{
  "email":"mzkhan886@gmail.com",
  "code":"958128",
  "newPassword":"password123"
}
